language: go
sudo: false
go:
  - 1.7
  - 1.8
  - 1.9
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci -race -package github.com/go-cmd/cmd -show
